### ISSUE TITLE
Add option for send message all friends in .txt

### ISSUE THREAD

**Issue by Dazmed707** [pedromgdo/Spammy-the-bot#1]
Please add an option that sends the specified message to all friends with the ID saved in a .txt
or the program can search for friends and save them in a .txt file to do spam later

**Comment by antoniomsantos99** [comment]
Hello there! We created an Alpha branch which currently supports list of ids that might suit your needs. However as the name implies it's still under development but feel free to mess around with it and report any bugs that you find!!

Best Regards!
António

**Comment by Cyb3rG0D7** [comment]
How to download tree aplha?

**Comment by antoniomsantos99** [comment]
You can click on branches on the main repository and choose Alpha or access from here: https://github.com/pedromgdo/Spammy-the-bot/tree/alpha

Then you can download how you would normally!

**Comment by Cyb3rG0D7** [comment]
It would also be good if you make the name and its version 0.2 in hexadecimal
How to download tree aplha?
YOU CAN USE THIS PAGE FOR GENERAL THE NAME
https://www.topster.es/texto-ascii/letters.html

**Comment by pedromgdo** [comment]
Thank you but we're aiming for a more simple look that works well on all devices.

**Comment by Cyb3rG0D7** [comment]
I would like the program to create an "output" folder where the id lists are in txt
It may be the program that generates them or one that was asked and says which list to use for spam
or ask for the route of the identification list in txt

**Comment by Cyb3rG0D7** [comment]
to create the ID list
i use fbi
the get_info option
then dump_id
and create me the .txt with the id of all my friends
https://github.com/xHak9x/fbi

**Comment by antoniomsantos99** [comment]
I added an option to import and export ids in the alpha branch however it is not currently tied to the main application. To import and export it just run SpammyIO.py

In future updates this feature may be added to the main app.

**Comment by Cyb3rG0D7** [comment]
Not Found SpammyIO.PY
![image](https://user-images.githubusercontent.com/35184132/72186103-75b9bc00-33c2-11ea-9ea5-46e48248455c.png)

**Comment by antoniomsantos99** [comment]
Ahh, my bad! Should be working now!

**Comment by Cyb3rG0D7** [comment]
You can now create the ID list

but when selecting does not happen from there
![image](https://user-images.githubusercontent.com/35184132/72187896-ebc02200-33c6-11ea-9d24-ce4a022eb945.png)

**Comment by antoniomsantos99** [comment]
The created IDList should be on the json file. If you want to get it in txt format you need to export it using SpammyIO.gui

**Comment by Cyb3rG0D7** [comment]
I have a list of ID in .txt
use SPammyIO.py to export it to json and it stays in that part.

**Comment by Cyb3rG0D7** [comment]
I have a list of ID in .txt
use SPammyIO.py to export it to json and it stays in that part.

**Comment by Cyb3rG0D7** [comment]
Here is a video of what I am doing.
[Uploading testspammy.zip…]()

**Comment by Cyb3rG0D7** [comment]
Here is a video of what I am doing.
[testspammy.zip](https://github.com/pedromgdo/Spammy-the-bot/files/4048197/testspammy.zip)

**Comment by Dazmed707** [comment]
Date release Spammy stable?

**Comment by Dazmed707** [comment]
Dead project?

**Comment by pedromgdo** [comment]
Yes.

**Comment by Dazmed707** [comment]
if the project is dead
file it

**Comment by pedromgdo** [comment]
The project is complete, it will not recieve any updates unless necessary, what you asked is not a planned feature and will not be implemented. It will only recieve updates if something is broken and not to add new features.

**Comment by Dazmed707** [comment]
it doesn't work well for me, it doesn't send the specific message to everyone
in addition they said that it would make the GUI for all the functions, convert to .json etc from a single script
In projects is what they planned to do and still need to finish that :/
