### ISSUE TITLE
Spammy.py file seems to be unable to execute.

### ISSUE THREAD

**Issue by TheStar01** [pedromgdo/Spammy-the-bot#6]
It crashes on startup.

**Comment by pedromgdo** [comment]
Have you read the updated README file?
Login information is now stored in an YML file, and there is now a requirements.txt file to install dependencies.

**Comment by TheStar01** [comment]
Yes, sorry I am ignorant at this subject. I created a yml file with my credentials.

Edit: I managed to open the .py file but it gives me this;

Attempt #1 failed, retrying
Traceback (most recent call last):
  File "C:\Users\computer\AppData\Local\Programs\Python\Python39\lib\site-packages\fbchat\_client.py", line 205, in login
    self._state = State.login(
  File "C:\Users\computer\AppData\Local\Programs\Python\Python39\lib\site-packages\fbchat\_state.py", line 151, in login
    return cls.from_session(session=session)
  File "C:\Users\computer\AppData\Local\Programs\Python\Python39\lib\site-packages\fbchat\_state.py", line 190, in from_session
    revision = int(r.text.split('"client_revision":', 1)[1].split(",", 1)[0])
IndexError: list index out of range

**Comment by pedromgdo** [comment]
Don't worry!
The ```$``` just means that the command that follows should be used in the terminal.
Also, I've created an issue explaining why the bot is not working at the moment, we're using an API which got declared unmaintained, so while that API is not updated Spammy will not work, unfortunately.

**Comment by TheStar01** [comment]
> Don't worry!
> The `$` just means that the command that follows should be used in the terminal.
> Also, I've created an issue explaining why the bot is not working at the moment, we're using an API which got declared unmaintained, so while that API is not updated Spammy will not work, unfortunately.

OK, thank you for your interest. Good luck on your next projects.
